services:
  keycloak-postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${POSTGRES_KEYCLOAK_USER:?Missing env POSTGRES_KEYCLOAK_USER}
      POSTGRES_PASSWORD: ${POSTGRES_KEYCLOAK_PASSWORD:?Missing env POSTGRES_KEYCLOAK_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRES_KEYCLOAK_USER", "-d", "keycloak"]
      interval: 5s
      retries: 5
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    restart: unless-stopped
    command: start
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: ${POSTGRES_KEYCLOAK_USER:?Missing env POSTGRES_KEYCLOAK_USER}
      KC_DB_PASSWORD: ${POSTGRES_KEYCLOAK_PASSWORD:?Missing env POSTGRES_KEYCLOAK_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:?Missing env KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:?Missing env KEYCLOAK_ADMIN_PASSWORD}
      
      KC_HOSTNAME: ${KEYCLOAK_URL:?Missing env KEYCLOAK_URL}
      KC_PROXY: edge
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
    ports:
      - "${KEYCLOAK_PORT:?Missing env KEYCLOAK_PORT}:8080"
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    networks:
      - keycloak








  backend-postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: big-data-server
      POSTGRES_USER: ${POSTGRES_BACKEND_USER:?Missing env POSTGRES_BACKEND_USER}
      POSTGRES_PASSWORD: ${POSTGRES_BACKEND_PASSWORD:?Missing env POSTGRES_BACKEND_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRES_BACKEND_USER", "-d", "big-data-server"]
      interval: 5s
      retries: 5
    volumes:
      - backend_postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  backend:
    build:
      context: ./server
    restart: unless-stopped
    environment:
      PORT: 3000
      KEYCLOAK_URL: ${KEYCLOAK_URL:?Missing env KEYCLOAK_URL}
      KEYCLOAK_PROTOCOL: ${KEYCLOAK_PROTOCOL:?Missing env KEYCLOAK_PROTOCOL}
      KEYCLOAK_REALM: Big-data-server-users
      POSTGRES_BACKEND_DB: big-data-server
      POSTGRES_BACKEND_HOST: backend-postgres
      POSTGRES_BACKEND_USER: ${POSTGRES_BACKEND_USER:?Missing env POSTGRES_BACKEND_USER}
      POSTGRES_BACKEND_PASSWORD: ${POSTGRES_BACKEND_PASSWORD:?Missing env POSTGRES_BACKEND_PASSWORD}
    ports:
      - "${BACKEND_PORT:?Missing env BACKEND_PORT}:3000"
    depends_on:
      backend-postgres:
        condition: service_healthy
    networks:
      - backend








  frontend:
    build:
      context: ./client
    restart: unless-stopped
    environment:
      PORT: 80
      VITE_KEYCLOAK_URL: ${KEYCLOAK_URL:?Missing env KEYCLOAK_URL}
      VITE_KEYCLOAK_PROTOCOL: ${KEYCLOAK_PROTOCOL:?Missing env KEYCLOAK_PROTOCOL}
      VITE_KEYCLOAK_REALM: Big-data-server-users
      VITE_BACKEND_URL: ${BACKEND_URL:?Missing env BACKEND_URL}
      VITE_BACKEND_PROTOCOL: ${BACKEND_PROTOCOL:?Missing env BACKEND_PROTOCOL}
    args:
      VITE_BACKEND_URL: ${BACKEND_URL}
      VITE_KEYCLOAK_URL: ${KEYCLOAK_URL}
      VITE_BACKEND_PROTOCOL: ${BACKEND_PROTOCOL}
      VITE_KEYCLOAK_PROTOCOL: ${KEYCLOAK_PROTOCOL}
    ports:
      - "${FRONTEND_PORT:?Missing env FRONTEND_PORT}:80"
    networks:
      - frontend








volumes:
  keycloak_postgres_data:
  backend_postgres_data:

networks:
  keycloak:
  backend:
  frontend:
